import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from '@/context/AuthProviders'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.className}`}>
        <NextAuthProvider>
        <Navbar />
          <main className="container mx-auto dark:bg-gray-100 dark:text-gray-900">
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  )
}
